name: "$(Date:yyyyMMdd)-Automatic semantic versioning"

on:
  push:
    branches:
      - 'features/*'
      - 'hotfix/*'
      - 'releases/*'
  pull_request:
    branches:
      - main
      - 'features/*'
      - 'hotfix/*'
      - 'releases/*'

jobs:  
    steps:
      - checkout: self

      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      - task: gitversion/execute@0
        displayName: Determine SemVer  
        inputs:
          useConfigFile: True
          configFilePath: ".azuredevops/gitversion.yml"

      - task: AzurCLI@2
        displayName: Update Build.BuildNumber
        inputs: 
          inlineScript: |
            Write-Host "##vso[task.setvariable variable=newBuildNumber]$(GitVersion.MajorMinorPatch)"

      - task: PowerShell@2
        displayName: Adding git release tag
        inputs:
          targetType: inline
          script: |
            git tag -a $("v$(setVariables.newBuildNumber)") -m $("Release $(setVariables.newBuildNumber)")
            Write-Host "Doing git push.." -ForegroundColor Cyan
            git push --tags
            Write-Host "Done." -ForegroundColor Cyan  