#infra-deployment.yml
 
trigger: none # Triggered defined none;deployment manual

name: "$(Date:yyyyMMdd)-${{parameters.enviroment}} infra deployment" 
parameters:
- name: enviorment
  displayName: "Enviorment"
  type: string
  default: dev
  values:
  - "dev"
  - "stage"
  - "prod"

variables:
 - template: ${{format('../../env/{0}/config.yml', parameters.enviroment) }}
 - name: paramsJSON
   value: ${{format('../../env/{0}/params-infra.json', parameters.enviroment) }}

pool: 
  vmImage: ubuntu-latest

stages:
 - stage: Lint
   displayName: Run Lint 
   jobs:
    - job: LintJob
      displayName: Lint Job
      steps: 
       - checkout: self
       - task: AzureCli@2
         name: Linting
         displayName: Linting
         inputs:
          azureSubscription: $(serviceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
           az bicep build --file ../../bicep/main/main-infra.bicep

 - stage: Validate 
   displayName: Run Validate
   jobs: 
    - job: ValidateJob
      displayName: Validate
      steps:
       - checkout: self
       - task: AzureCli@2
         name: Validating
         displayName: Validating
         inputs:
          azureSubscription: $(serviceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
           az deployment group validate --resource-group $(resourceGroupName) \
           --template-file ../../bicep/main/main-infra.bicep \
           --parameters ../../env/${{parameters.enviorment}}/params-infra.json

 - stage: Deploy 
   displayName: Run Deploy
   jobs:    
    - job: DeployJob
      displayName: Deploy Job
      steps:
       - checkout: self
        # Install GitVersion
       - task: gitversion/setup@0
         displayName: Install GitVersion
         inputs:
          versionSpec: "5.x"

       - task: GitVersion@5
         displayName: 'Get Version'
         inputs:
           runtime: 'netcore'  # Adjust if needed
           configFilePath: '.azuredevops/gitversion.yml'
         name: GetVersion  # Naming the task for later reference

       - task: AzureCli@2
         name: Deploying
         displayName: Deploying
         inputs:
          azureSubscription: $(serviceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScripts: |
           az deployment group create --resource-group$(resourceGroupName) --template-file ../../bicep/main/main-infra.bicep --parameters ../../env/${{parameters.enviorment}}/params-infra.json
           # Capture the result of the deployment
            if [ $? -eq 0 ]; then
              echo "Deployment succeeded."
              echo "Current Version: $(GitVersion.SemVer)"  # Print current version
              
              # Increment version logic here
              echo "Incrementing version..."
              # Call a script or command to update the version in GitVersion.yml or wherever it is stored.
            else
              echo "Deployment failed, version not incremented."
            fi